Repository masil-team/Back-End, pull requests merged in 2023-02, with the labels that each got.

#41 Feat : 17 주소 검색 기능
  src/main/java/com/masil/domain/address/controller/AddressController.java
  src/main/java/com/masil/domain/address/dto/request/AddressRequest.java
  src/main/java/com/masil/domain/address/dto/response/AddressResponse.java
  src/main/java/com/masil/domain/address/dto/response/AddressSearchResponse.java
  src/main/java/com/masil/domain/address/entity/EmdAddress.java
  src/main/java/com/masil/domain/address/entity/SggAddress.java
  src/main/java/com/masil/domain/address/entity/SidoAddress.java
  src/main/java/com/masil/domain/address/repository/EmdAddressRepository.java
  src/main/java/com/masil/domain/address/repository/SggAddressRepository.java
  src/main/java/com/masil/domain/address/service/AddressService.java
  src/main/java/com/masil/domain/address/service/AddressServiceImpl.java
  src/main/java/com/masil/domain/member/entity/Member.java
  src/main/java/com/masil/domain/member/entity/MemberAddress.java
  src/main/java/com/masil/domain/member/repository/MemberAddressRepository.java
  src/test/java/com/masil/domain/address/service/AddressServiceTest.java
  src/test/resources/address/20230201/emd_address_test_202302011004.csv
  src/test/resources/address/20230201/sgg_address_test_202302011004.csv
  src/test/resources/address/20230201/sido_address_test_202302011003.csv
Labels: feature

#44 refactor : post 로직 관련 버그 수정 및 개선
  .gitignore
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostDetailResponse.java
  src/main/java/com/masil/domain/post/dto/PostsElementResponse.java
  src/main/java/com/masil/domain/post/dto/PostsResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/resources/static/docs/api.html
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: bug, chore, refactor

#46 chore : 쓸모없는 import문 제거
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostCreateRequest.java
  src/main/java/com/masil/domain/post/dto/PostDetailResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/controller/PostLikeController.java
  src/main/java/com/masil/domain/postlike/entity/PostLike.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
  src/test/java/com/masil/domain/postlike/service/PostLikeServiceTest.java
Labels: chore

#51 feat: Comment 대댓글 기능 추가 / commentLike dto 변환 (#40)
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/ChildrenCreateRequest.java
  src/main/java/com/masil/domain/comment/dto/ChildrenResponse.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/controller/CommentLikeController.java
  src/main/java/com/masil/domain/commentlike/dto/CommentLikeResponse.java
  src/main/java/com/masil/domain/commentlike/entity/CommentLike.java
  src/main/java/com/masil/domain/commentlike/service/CommentLikeService.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
Labels: feature, refactor

#49 refactor : 주소 검색 기능
  src/main/java/com/masil/domain/address/controller/AddressController.java
  src/main/java/com/masil/domain/address/dto/response/AddressSearchResponse.java
  src/main/java/com/masil/domain/address/service/AddressService.java
  src/main/java/com/masil/domain/address/service/AddressServiceImpl.java
  src/main/java/com/masil/domain/member/entity/Member.java
  src/main/java/com/masil/domain/member/entity/MemberAddress.java
  src/main/java/com/masil/domain/member/repository/MemberAddressRepository.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/address/controller/AddressControllerTest.java
  src/test/java/com/masil/domain/address/service/AddressServiceTest.java
Labels: chore, refactor

#56 feat : Comment 조회 / CommentControllerTest 수정 (#55)
  src/docs/asciidoc/comment.adoc
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/exception/CommentInputException.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/masil/domain/comment/dto/ChildrenCommentCreateRequestBuilder.java
  src/test/java/com/masil/domain/comment/dto/CommentCreate411RequestBuilder.java
  src/test/java/com/masil/domain/commentlike/controller/CommentLikeControllerTest.java
Labels: feature, refactor

#57 refactor : auth 이메일 중복 처리 , 재발행 코드 추가 및 코드 정리
  src/main/java/com/masil/domain/member/controller/MemberController.java
  src/main/java/com/masil/domain/member/dto/request/MemberAddressRequest.java
  src/main/java/com/masil/domain/member/entity/Member.java
  src/main/java/com/masil/domain/member/repository/MemberRepository.java
  src/main/java/com/masil/domain/member/service/MemberService.java
  src/main/java/com/masil/global/auth/controller/AuthController.java
  src/main/java/com/masil/global/auth/dto/request/AuthTokenRequest.java
  src/main/java/com/masil/global/auth/dto/request/SignupRequest.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtExceptionHandlerFilter.java
  src/main/java/com/masil/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/main/java/com/masil/global/config/security/JwtSecurityConfig.java
  src/main/java/com/masil/global/config/security/SecurityConfig.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/member/service/MemberServiceTest.java
  src/test/java/com/masil/global/auth/service/AuthServiceTest.java
Labels: refactor

#58 refactor : post에 @where 적용
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
Labels: refactor

#60 feat : yml파일 수정
  src/main/resources/application-share.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: feature

#63 feat : CommentFind isOwner, isLiked 추가 (#62)
  src/docs/asciidoc/comment.adoc
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/ChildrenResponse.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/repository/CommentLikeRepository.java
  src/main/java/com/masil/domain/commentlike/service/CommentLikeService.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
Labels: feature

#61 feat : member 로그인한 유저 정보 조회 api 추가
  src/main/java/com/masil/domain/member/controller/MemberController.java
  src/main/java/com/masil/global/auth/controller/AuthController.java
  src/main/java/com/masil/global/auth/dto/response/CurrentMember.java
  src/main/java/com/masil/global/auth/dto/response/LoginMemberInfoResponse.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
Labels: feature

#65 chore : 서브모듈 브랜치 설정
  .gitmodules
Labels: chore

#74 Refactor : post 관련 리펙토링
  src/main/java/com/masil/domain/board/entity/Board.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/service/PostLikeService.java
  src/test/java/com/masil/domain/fixture/BoardFixture.java
  src/test/java/com/masil/domain/fixture/MemberFixture.java
  src/test/java/com/masil/domain/fixture/PostFixture.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
  src/test/java/com/masil/domain/postlike/service/PostLikeServiceTest.java
Labels: chore, refactor

#77 feat : comment 조회 부모댓글 deleted 추가 (#76)
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/post/entity/State.java
  src/main/java/com/masil/global/common/entity/BaseEntity.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
Labels: feature, refactor

#71 refactor : 재발행 , 로그인 유저 정보 코드 수정
  src/main/java/com/masil/domain/address/controller/AddressController.java
  src/main/java/com/masil/domain/address/dto/response/AddressResponse.java
  src/main/java/com/masil/domain/address/entity/EmdAddress.java
  src/main/java/com/masil/domain/address/entity/SggAddress.java
  src/main/java/com/masil/domain/address/service/AddressService.java
  src/main/java/com/masil/domain/member/entity/Member.java
  src/main/java/com/masil/global/auth/dto/response/CurrentMember.java
  src/main/java/com/masil/global/auth/dto/response/LoginMemberInfoResponse.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtExceptionHandlerFilter.java
  src/main/java/com/masil/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/global/auth/service/AuthServiceTest.java
Labels: refactor

#88 Feat : 인증 - 로그아웃
  src/main/java/com/masil/global/auth/controller/AuthController.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/test/java/com/masil/global/auth/service/AuthServiceTest.java
Labels: feature

#90 ref : commentFind query 수정
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/ChildrenResponse.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/exception/CommentInputException.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/dto/CommentLikeResponse.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
Labels: bug, chore, refactor

#91 Feat : 알람(notification) 기능 구현
  src/main/java/com/masil/domain/notification/controller/NotificationController.java
  src/main/java/com/masil/domain/notification/dto/NotificationDto.java
  src/main/java/com/masil/domain/notification/dto/NotificationResponse.java
  src/main/java/com/masil/domain/notification/dto/NotificationsResponse.java
  src/main/java/com/masil/domain/notification/entity/Notification.java
  src/main/java/com/masil/domain/notification/entity/NotificationType.java
  src/main/java/com/masil/domain/notification/repository/EmitterRepository.java
  src/main/java/com/masil/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/masil/domain/notification/repository/NotificationRepository.java
  src/main/java/com/masil/domain/notification/service/NotificationService.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/postlike/service/PostLikeService.java
  src/test/java/com/masil/domain/notification/service/NotificationServiceTest.java
Labels: feature

#83 refactor : 비회원 요청 가능한 인증 uri 패턴
  src/main/java/com/masil/domain/member/controller/MemberController.java
  src/main/java/com/masil/domain/member/service/MemberService.java
  src/main/java/com/masil/global/auth/controller/AuthController.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/main/java/com/masil/global/config/properties/AccessRequestMatcherAdapter.java
  src/main/java/com/masil/global/config/security/JwtSecurityConfig.java
  src/main/java/com/masil/global/config/security/SecurityConfig.java
  src/main/java/com/masil/global/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/masil/common/annotation/ControllerMockApiTest.java
  src/test/java/com/masil/domain/address/controller/AddressControllerTest.java
  src/test/java/com/masil/domain/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/masil/domain/postlike/controller/PostLikeControllerTest.java
  src/test/java/com/masil/global/auth/service/AuthServiceTest.java
Labels: refactor

#95 bug : 허용 요청 URI 패턴 수정
  src/main/java/com/masil/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/masil/global/config/properties/AccessRequestMatcherAdapter.java
  src/main/java/com/masil/global/config/security/SecurityConfig.java
Labels: bug

#97 ref : post 검색 (#81)
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/dto/CommentsResponse.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/entity/SearchQuery.java
  src/main/java/com/masil/domain/post/exception/PostSearchInputException.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/global/auth/service/AuthServiceTest.java
Labels: bug, feature
