Repository masil-team/Back-End, pull requests merged in 2023-03, with the labels that each got.

#101 ref : post 검색 rCode 추가
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
Labels: refactor

#102 Refactor : notification 수정
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/service/CommentLikeService.java
  src/main/java/com/masil/domain/notification/controller/NotificationController.java
  src/main/java/com/masil/domain/notification/dto/NotificationDto.java
  src/main/java/com/masil/domain/notification/dto/NotificationResponse.java
  src/main/java/com/masil/domain/notification/dto/NotificationsResponse.java
  src/main/java/com/masil/domain/notification/entity/Notification.java
  src/main/java/com/masil/domain/notification/exception/NotificationAccessDeniedException.java
  src/main/java/com/masil/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/masil/domain/notification/repository/EmitterRepository.java
  src/main/java/com/masil/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/masil/domain/notification/repository/NotificationRepository.java
  src/main/java/com/masil/domain/notification/service/NotificationService.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/masil/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/masil/global/auth/service/AuthServiceTest.java
Labels: feature, refactor

#104 bug : 전체 카테고리 제대로 조회되도록 수정
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/test/java/com/masil/domain/post/dto/PostFilterRequestBuilder.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: bug

#108 Refactor : 상세 게시글 이미지 개수 컬럼추가, 이미지 업로드 일부 수정 + 테스트 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/post/dto/PostDetailResponse.java
  src/main/java/com/masil/domain/postFile/service/PostFileService.java
  src/main/java/com/masil/domain/storage/dto/FileInfoDto.java
  src/main/java/com/masil/domain/storage/exception/FileNotFoundException.java
  src/main/java/com/masil/domain/storage/exception/InvalidImageExtensionException.java
  src/main/java/com/masil/domain/storage/exception/InvalidImageFileException.java
  src/main/java/com/masil/domain/storage/service/AwsS3Service.java
  src/main/java/com/masil/global/error/GlobalExceptionHandler.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/main/java/com/masil/global/error/exception/InvalidValueException.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/storage/controller/AwsS3ControllerTest.java
  src/test/java/com/masil/domain/storage/service/AwsS3ServiceTest.java
  src/test/resources/image/txt.jpg
Labels: refactor, test

#110 젠킨스 테스트용 pr 입니다.
  src/main/resources/application-share.yml
Labels: chore, devops, develop

#111 feat : 마이페이지 내정보 조회
  src/main/java/com/masil/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/masil/domain/bookmark/service/BookmarkService.java
  src/main/java/com/masil/domain/comment/dto/CommentsResponse.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/repository/CommentLikeRepository.java
  src/main/java/com/masil/domain/commentlike/service/CommentLikeService.java
  src/main/java/com/masil/domain/member/controller/MyController.java
  src/main/java/com/masil/domain/member/dto/request/MyFindRequest.java
  src/main/java/com/masil/domain/member/dto/response/LikeFindResponse.java
  src/main/java/com/masil/domain/member/dto/response/MyFindResponse.java
  src/main/java/com/masil/domain/member/dto/response/MyPostReponse.java
  src/main/java/com/masil/domain/member/service/MyService.java
  src/main/java/com/masil/domain/member/service/MyServiceImpl.java
  src/main/java/com/masil/domain/post/dto/PostsResponse.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/post/util/PostPermissionUtil.java
  src/main/java/com/masil/domain/postlike/repository/PostLikeRepository.java
  src/main/java/com/masil/domain/postlike/service/PostLikeService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/masil/domain/fixture/AddressFixture.java
  src/test/java/com/masil/domain/fixture/CommentFixture.java
  src/test/java/com/masil/domain/fixture/MemberFixture.java
  src/test/java/com/masil/domain/fixture/PostFixture.java
  src/test/java/com/masil/domain/member/controller/MyControllerTest.java
  src/test/java/com/masil/domain/member/service/MyServiceTest.java
Labels: feature

#116 chore : 마이페이지 내정보 조회 RequestBody -> PathValiable로 변경
  src/main/java/com/masil/domain/member/controller/MyController.java
Labels: bug, chore, dev-server

#119 Refactor : 자잘한 리펙토링
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/service/PostLikeService.java
  src/main/java/com/masil/global/common/entity/BaseEntity.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: refactor
