Repository masil-team/Back-End, pull requests merged in 2023-01, with the labels that each got.

#2 Feat: 게시글 생성, 단 건, 다 건 조회 초기 단계 구현
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostCreateRequest.java
  src/main/java/com/masil/domain/post/dto/PostResponse.java
  src/main/java/com/masil/domain/post/dto/PostsResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/entity/State.java
  src/main/java/com/masil/domain/post/exception/PostNotFoundException.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/user/repository/UserRepository.java
  src/main/resources/application-test.yml
  src/test/java/com/masil/controller/PostControllerTest.java
  src/test/java/com/masil/service/PostServiceTest.java
  src/test/resources/application.yml
Labels: feature

#4 Feat : 게시글 수정, 삭제 초기 단계 구현
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostModifyRequest.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/user/entity/User.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/masil/controller/PostControllerTest.java
  src/test/java/com/masil/service/PostServiceTest.java
Labels: feature

#7 Feat : 로그인 , 회원가입 (#5)
  build.gradle
  src/main/java/com/masil/domain/user/controller/UserController.java
  src/main/java/com/masil/domain/user/dto/UserCreateRequest.java
  src/main/java/com/masil/domain/user/dto/UserLoginRequest.java
  src/main/java/com/masil/domain/user/dto/UserResponse.java
  src/main/java/com/masil/domain/user/entity/User.java
  src/main/java/com/masil/domain/user/repository/UserRepository.java
  src/main/java/com/masil/domain/user/service/CustomUserDetailService.java
  src/main/java/com/masil/domain/user/service/UserService.java
  src/main/java/com/masil/global/auth/config/SecurityConfig.java
  src/main/java/com/masil/global/auth/jwt/component/JwtTokenProvider.java
  src/main/java/com/masil/global/auth/jwt/config/JwtPropertiesConfig.java
  src/main/java/com/masil/global/auth/jwt/dto/TokenInfo.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/masil/global/auth/jwt/properties/JwtProperties.java
  src/main/java/com/masil/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/masil/global/error/response/ErrorResponse.java
  src/main/resources/application-share.yml
  src/test/java/com/masil/domain/user/controller/UserControllerTest.java
  src/test/java/com/masil/domain/user/service/UserServiceTest.java
Labels: feature

#8 feat : spring rest docs 적용
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/post/dto/PostResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/resources/static/docs/api.html
  src/test/java/com/masil/controller/PostControllerTest.java
  src/test/java/com/masil/service/PostServiceTest.java
Labels: feature

#11 refactor : 기존 post 테스트 코드 리펙토링
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/user/controller/UserController.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/masil/common/DatabaseCleaner.java
  src/test/java/com/masil/common/annotation/ServiceTest.java
  src/test/java/com/masil/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/dto/PostCreateRequestBuilder.java
  src/test/java/com/masil/domain/post/dto/PostModifyRequestBuilder.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
  src/test/java/com/masil/domain/user/controller/UserControllerTest.java
  src/test/java/com/masil/domain/user/service/UserServiceTest.java
  src/test/java/com/masil/service/PostServiceTest.java
Labels: feature, refactor

#15 Feat: comment CRUD 초기 작업
  src/main/java/com/masil/MasilApplication.java
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/CommentCreateRequest.java
  src/main/java/com/masil/domain/comment/dto/CommentModifyRequest.java
  src/main/java/com/masil/domain/comment/dto/CommentRequest.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/masil/domain/comment/service/CommentServiceTest.java
Labels: feature

#19 refator : post 현재까지 구현 작업물 리펙토링
  .gitignore
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostDetailResponse.java
  src/main/java/com/masil/domain/post/dto/PostResponse.java
  src/main/java/com/masil/domain/post/dto/PostsElementResponse.java
  src/main/java/com/masil/domain/post/dto/PostsResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/repository/PostLikeRepository.java
  src/main/resources/application.yml
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: refactor

#21 refactor : post api 반환 형식 변경
  src/main/java/com/masil/domain/member/dto/response/MemberResponse.java
  src/main/java/com/masil/domain/post/dto/PostDetailResponse.java
  src/main/java/com/masil/domain/post/dto/PostsElementResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: chore, refactor

#22 fix : 날짜에 null 들어가는 버그 수정
  src/main/java/com/masil/MasilApplication.java
Labels: hotfix

#24 feat : post 페이징 기능 추가
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostsResponse.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: bug, feature

#27 feat : post 좋아요 기능 구현
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/controller/PostLikeController.java
  src/main/java/com/masil/domain/postlike/dto/PostLikeResponse.java
  src/main/java/com/masil/domain/postlike/entity/PostLike.java
  src/main/java/com/masil/domain/postlike/repository/PostLikeRepository.java
  src/main/java/com/masil/domain/postlike/service/PostLikeService.java
  src/main/java/com/masil/global/config/security/SecurityConfig.java
  src/main/resources/static/docs/api.html
  src/test/java/com/masil/common/annotation/ControllerMockApiTest.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/postlike/controller/PostLikeControllerTest.java
  src/test/java/com/masil/domain/postlike/service/PostLikeServiceTest.java
Labels: feature

#30 feat : 글로벌 예외 수정 + post 관련 예외 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/masil/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/masil/domain/post/exception/PostAccessDeniedException.java
  src/main/java/com/masil/domain/post/exception/PostNotFoundException.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/exception/SelfPostLikeException.java
  src/main/java/com/masil/domain/postlike/service/PostLikeService.java
  src/main/java/com/masil/global/error/ErrorResponse.java
  src/main/java/com/masil/global/error/GlobalExceptionHandler.java
  src/main/java/com/masil/global/error/exception/EntityNotFoundException.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/main/java/com/masil/global/error/exception/NoAuthenticationException.java
  src/main/resources/static/docs/api.html
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
  src/test/java/com/masil/domain/postlike/controller/PostLikeControllerTest.java
  src/test/java/com/masil/domain/postlike/service/PostLikeServiceTest.java
Labels: feature, refactor

#29 Feat: comment 조회 page 처리 / Comment ControllerTest (#28)
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/CommentCreateRequest.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/entity/CommentLike.java
  src/main/java/com/masil/domain/commentlike/repository/CommentLikeRepository.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/masil/domain/comment/dto/CommentCreateRequestBuilder.java
  src/test/java/com/masil/domain/comment/dto/CommentModifyRequestBuilder.java
  src/test/java/com/masil/domain/comment/service/CommentServiceTest.java
Labels: feature

#31 refactor : Spring Security 인증 기능 수정
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/global/auth/annotaion/LoginUser.java
  src/main/java/com/masil/global/auth/dto/response/AuthMemberAdaptor.java
  src/main/java/com/masil/global/auth/dto/response/CurrentMember.java
  src/main/java/com/masil/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/masil/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/masil/global/auth/service/AuthService.java
  src/main/java/com/masil/global/auth/service/CustomUserDetailsService.java
  src/main/java/com/masil/global/config/security/JwtSecurityConfig.java
  src/main/java/com/masil/global/config/security/SecurityConfig.java
Labels: refactor

#33 feat : post 관련하여 controller member 정보 추가
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostCreateRequest.java
  src/main/java/com/masil/domain/post/dto/PostDetailResponse.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/domain/postlike/controller/PostLikeController.java
  src/main/java/com/masil/global/config/security/SecurityConfig.java
  src/main/resources/static/docs/api.html
  src/test/java/com/masil/common/annotation/ControllerMockApiTest.java
  src/test/java/com/masil/common/security/WithMockCustomUser.java
  src/test/java/com/masil/common/security/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
Labels: bug, feature

#36 Feat: commentLike 초기 기능 (#34)
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/domain/commentlike/controller/CommentLikeController.java
  src/main/java/com/masil/domain/commentlike/entity/CommentLike.java
  src/main/java/com/masil/domain/commentlike/exception/SelfCommentLikeException.java
  src/main/java/com/masil/domain/commentlike/repository/CommentLikeRepository.java
  src/main/java/com/masil/domain/commentlike/service/CommentLikeService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
Labels: feature

#39 ref: Comment CurrentMember 기능 추가 / controllerTest 수정(#37)
  src/main/java/com/masil/domain/comment/controller/CommentController.java
  src/main/java/com/masil/domain/comment/dto/CommentCreateRequest.java
  src/main/java/com/masil/domain/comment/dto/CommentResponse.java
  src/main/java/com/masil/domain/comment/entity/Comment.java
  src/main/java/com/masil/domain/comment/exception/CommentAccessDeniedException.java
  src/main/java/com/masil/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/masil/domain/comment/repository/CommentRepository.java
  src/main/java/com/masil/domain/comment/service/CommentService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/masil/domain/comment/service/CommentServiceTest.java
Labels: feature, refactor

#42 feat : 카테고리 추가
  src/main/java/com/masil/domain/board/entity/Board.java
  src/main/java/com/masil/domain/board/exception/BoardNotFoundException.java
  src/main/java/com/masil/domain/board/repository/BoardRepository.java
  src/main/java/com/masil/domain/post/controller/PostController.java
  src/main/java/com/masil/domain/post/dto/PostCreateRequest.java
  src/main/java/com/masil/domain/post/dto/PostModifyRequest.java
  src/main/java/com/masil/domain/post/entity/Post.java
  src/main/java/com/masil/domain/post/repository/PostRepository.java
  src/main/java/com/masil/domain/post/service/PostService.java
  src/main/java/com/masil/global/error/exception/ErrorCode.java
  src/test/java/com/masil/domain/post/controller/PostControllerTest.java
  src/test/java/com/masil/domain/post/dto/PostCreateRequestBuilder.java
  src/test/java/com/masil/domain/post/dto/PostModifyRequestBuilder.java
  src/test/java/com/masil/domain/post/service/PostServiceTest.java
Labels: feature, refactor
